---
name: test

on:
  push:
    branches:
      - main
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: pip install
        run: pip install -r updatecli.d/requirements.txt

      - name: Generate workflows
        run: |
          ls -l 
          python3 --version
          mkdir /tmp/workflows
          python updatecli.d/updatecli_workflow_generator.py
          ls -l /tmp
          ls -l /tmp/workflows

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2

      - name: Run Updatecli in apply mode
        run: updatecli apply --config /tmp/workflows
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ secrets.GH_USERNAME }}
